// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAbqjxskXGGrosjI9pnk0cwNxba4ajLBw',
    appId: '1:1065685017916:web:f4a7f65933167caa37aa39',
    messagingSenderId: '1065685017916',
    projectId: 'nyro-crypto',
    authDomain: 'nyro-crypto.firebaseapp.com',
    storageBucket: 'nyro-crypto.firebasestorage.app',
    measurementId: 'G-BRVSTKC4VX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFv7zPl33lIXkvinNumzin7ss4TnzIM3k',
    appId: '1:1065685017916:android:2ce95ffb913e360d37aa39',
    messagingSenderId: '1065685017916',
    projectId: 'nyro-crypto',
    storageBucket: 'nyro-crypto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfGzJSppS0PubhKa0sK-DTGdHxol8fSRE',
    appId: '1:1065685017916:ios:4401a648a0bc8f6b37aa39',
    messagingSenderId: '1065685017916',
    projectId: 'nyro-crypto',
    storageBucket: 'nyro-crypto.firebasestorage.app',
    iosBundleId: 'com.example.nyroCryto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfGzJSppS0PubhKa0sK-DTGdHxol8fSRE',
    appId: '1:1065685017916:ios:4401a648a0bc8f6b37aa39',
    messagingSenderId: '1065685017916',
    projectId: 'nyro-crypto',
    storageBucket: 'nyro-crypto.firebasestorage.app',
    iosBundleId: 'com.example.nyroCryto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAbqjxskXGGrosjI9pnk0cwNxba4ajLBw',
    appId: '1:1065685017916:web:8240f2c4713c79b737aa39',
    messagingSenderId: '1065685017916',
    projectId: 'nyro-crypto',
    authDomain: 'nyro-crypto.firebaseapp.com',
    storageBucket: 'nyro-crypto.firebasestorage.app',
    measurementId: 'G-SDYJPTWPX7',
  );
}
